# Workflow name
name: Resume Continuous Deployment

# Start pipeline on push to main.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# The list of jobs to run 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Configure AWS Credentials      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      # 3. Setup Node
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          
      # 4. Setup Cache
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 5. Build Angular
      - name: Build Angular
        run: |
          ls
          npm install
          ng build
          echo "Angular build completed"
          
      # 6. Copy to S3 Bucket
      - name: Copy to S3 Bucket
        run: |
          aws s3 cp ./dist/* s3://amazon-cloudfront-secure-static-site-s3bucketroot-6jd606vo4pso
          
      # 7. Invalidate CloudFront
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E1OZM9PME8EIMR --paths "/*"
